from turtle import*
import turtle

title("EJ Prince D. Sevilleno - Midterm - Mandala Art")
turtle.speed(20)

for i in range(25):
    for colour in ['#4169E1']:
        color(colour)
        begin_fill()
        left(15)
        forward(230)
        left(90)
        forward(230)
        left(90)
        forward(230)
        left(90)
        forward(230)
        left(90)
        end_fill()

for i in range(25):
    for colour in ['white']:
        color(colour)
        begin_fill()
        left(15)
        forward(221)
        left(90)
        forward(221)
        left(90)
        forward(221)
        left(90)
        forward(221)
        left(90)
        end_fill()

for i in range(25):
    for colour in ['#4169E1']:
        color(colour)
        begin_fill()
        left(15)
        forward(218)
        left(90)
        forward(218)
        left(90)
        forward(218)
        left(90)
        forward(218)
        left(90)
        end_fill()

color('white')
penup()
begin_fill()
right(90)
forward(285)
left(90)
pendown()
circle(285)
penup()
right(-90)
forward(285)
left(-90)
end_fill()
pendown()

color('#2E8B57')
penup()
begin_fill()
right(90)
forward(274)
left(90)
pendown()
circle(274)
penup()
right(-90)
forward(274)
left(-90)
end_fill()
pendown()

color('white')
pensize(5)
for i in range(35):
    circle(130)
    left(20)

color('#2E8B57')
penup()
begin_fill()
right(90)
forward(241)
left(90)
pendown()
circle(241)
penup()
right(-90)
forward(241)
left(-90)
end_fill()
pendown()

color('white')
pensize(5)
for i in range(35):
    circle(115)
    left(20)

color('#2E8B57')
penup()
begin_fill()
right(90)
forward(213)
left(90)
pendown()
circle(213)
penup()
right(-90)
forward(213)
left(-90)
end_fill()
pendown()

color('white')
penup()
begin_fill()
right(90)
forward(200)
left(90)
pendown()
circle(200)
penup()
right(-90)
forward(200)
left(-90)
end_fill()
pendown()

for i in range(25):
    for colour in ['#4169E1']:
        color(colour)
        begin_fill()
        left(15)
        forward(140)
        left(90)
        forward(140)
        left(90)
        forward(140)
        left(90)
        forward(140)
        left(90)
        end_fill()

color('white')
pensize(5)
for i in range(35):
    circle(90)
    left(20)

color('white')
pensize(5)
#begin_fill()
for i in range(50):
    circle(72)
    left(20)
#end_fill()

color('#DAA520')
pensize(5)
#begin_fill()
for i in range(35):
    circle(25)
    left(20)
#end_fill()



color('#FFD700')
#begin_fill()
for i in range(50):
    circle(100-i,90)
    left(90)
    circle(100-i,90)
    left(18)
#end_fill()

bgcolor('#FAFAD2')

turtle.exitonclick()
